nonterminalSymbols:
  # ? name
  ? A
  ? B
  ? C
  ? D
  ? S
terminalSymbols:
  # name: regex
  α: a
  β: b
ignoredSymbols:
startSymbol: S
productions:
  # - left part -> right part
  - S -> C β B A
  - A -> A α β
  - A -> α β
  - B -> C
  - B -> D β
  - C -> α
  - D -> α
